import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {export const metadata = {
  title: "Anas Makouan | Creative Strategist (Hybrid AI × Reels × Messaging)",
  description:
    "Creative strategist portfolio focused on AI-powered ideation systems, Reels performance frameworks, and messaging funnel architecture.",
  openGraph: {
    title: "Anas Makouan | Creative Strategist",
    description:
      "Hybrid AI × Reels × Messaging strategist. Case studies, systems, and Reels scripts.",
    url: "https://YOUR_VERCEL_URL.vercel.app",
    siteName: "Anas Makouan Portfolio",
    images: [
      {
        url: "/og-image.png",
        width: 1200,
        height: 630,
        alt: "Anas Makouan Portfolio",
      },
    ],
    locale: "en_CA",
    type: "website",
  },
};

  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
